# -*- coding: utf-8 -*-
"""Đánh giá tín dụng_3-4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K3Zi_Vg9gU6gzeHy8GARvg8xWtcThLZy
"""

# Upload excel file from local system
from google.colab import files
uploaded = files.upload()

# Cài đặt và import các thư viện cần thiết
!pip install imbalanced-learn xgboost
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

df_raw = pd.read_excel("Data_For Midterm and Final Project.xlsx")
df = df_raw.copy()
selected_columns = [
    'PHUONG THUC CHO VAY', 'LOAIKH', 'SEX', 'CURRENCYCD', 'DESC_TIME',
    'MJACCTTYPDESC', 'ORGNAME', 'PARENTORGNAME', 'MUCDICHVAY',"OPEN_DATE","NGAYDENHAN",
    'BASE_BAL', 'CURR_BAL', 'DUNO_QD', 'LAISUAT',"NHOMNOMOI"
]

# Lọc dataframe
df = df[selected_columns]

# Copy lại để xử lý
df["OPEN_DATE_clean"] = pd.NaT

# Với các dòng có giá trị là số (serial date)
mask_numeric = df["OPEN_DATE"].apply(lambda x: str(x).replace('.', '').isnumeric())

# Dòng là chuỗi ngày hợp lệ
mask_string = ~mask_numeric

# Áp dụng chuyển đổi với từng loại
df.loc[mask_numeric, "OPEN_DATE_clean"] = pd.to_datetime(df.loc[mask_numeric, "OPEN_DATE"].astype(float),
                                                         origin="1899-12-30", unit="D", errors="coerce")

df.loc[mask_string, "OPEN_DATE_clean"] = pd.to_datetime(df.loc[mask_string, "OPEN_DATE"],
                                                        format="%d/%m/%Y", errors="coerce")

# Kiểm tra kết quả
print(df[["OPEN_DATE", "OPEN_DATE_clean"]].head())


# 2. Đếm số lượng lỗi
num_invalid = invalid_dates.shape[0]
print(f"🛑 Số lượng giá trị lỗi trong OPEN_DATE_clean: {num_invalid}")

# 3. Hiển thị một số ví dụ lỗi (nếu có)
if num_invalid > 0:
    print("📋 Các giá trị gốc bị lỗi khi chuyển datetime:")
    display(invalid_dates[["OPEN_DATE"]].drop_duplicates().head(10))
else:
    print("✅ Không có lỗi nào trong OPEN_DATE_clean — tất cả đã chuyển đổi thành datetime thành công.")

# Tạo cột clean mặc định là NaT
df["NGAYDENHAN_clean"] = pd.NaT

# Mask số: kiểm tra nếu là số serial Excel
mask_numeric_ngay = df["NGAYDENHAN"].apply(lambda x: str(x).replace('.', '').isnumeric())

# Còn lại là chuỗi ngày (mask ngược lại)
mask_string_ngay = ~mask_numeric_ngay

# Chuyển đổi giá trị kiểu số (serial Excel)
df.loc[mask_numeric_ngay, "NGAYDENHAN_clean"] = pd.to_datetime(
    df.loc[mask_numeric_ngay, "NGAYDENHAN"].astype(float),
    origin="1899-12-30", unit="D", errors="coerce"
)

# Chuyển đổi giá trị kiểu chuỗi
df.loc[mask_string_ngay, "NGAYDENHAN_clean"] = pd.to_datetime(
    df.loc[mask_string_ngay, "NGAYDENHAN"],
    format="%d/%m/%Y", errors="coerce"
)

# Kiểm tra các giá trị lỗi (NaT)
invalid_ngay = df[df["NGAYDENHAN_clean"].isna()]

# Đếm số lỗi
num_invalid_ngay = invalid_ngay.shape[0]
print(f"🛑 Số lượng lỗi trong NGAYDENHAN_clean: {num_invalid_ngay}")

# Hiển thị một số ví dụ giá trị lỗi
if num_invalid_ngay > 0:
    print("📋 Các giá trị gốc bị lỗi khi chuyển datetime:")
    display(invalid_ngay[["NGAYDENHAN"]].drop_duplicates().head(10))
else:
    print("✅ Không có lỗi nào trong NGAYDENHAN_clean — tất cả đã chuyển đổi thành datetime thành công.")

df[["OPEN_DATE_clean", "NGAYDENHAN_clean"]].head()

# Kiểm tra min và max của OPEN_DATE_clean
open_min = df["OPEN_DATE_clean"].min()
open_max = df["OPEN_DATE_clean"].max()

# Kiểm tra min và max của NGAYDENHAN_clean
due_min = df["NGAYDENHAN_clean"].min()
due_max = df["NGAYDENHAN_clean"].max()

# In kết quả
print("📅 Thông tin thời gian:")
print(f"🗓️ OPEN_DATE_clean: từ {open_min.date()} đến {open_max.date()}")
print(f"📅 NGAYDENHAN_clean: từ {due_min.date()} đến {due_max.date()}")

# Bước 1: Xác định giá trị cần sửa
wrong_date = pd.to_datetime("2121-04-30")
correct_date = pd.to_datetime("2021-04-30")

# Bước 2: Cập nhật lại
df.loc[df["NGAYDENHAN_clean"] == wrong_date, "NGAYDENHAN_clean"] = correct_date

# Bước 3: Kiểm tra lại
print("✅ Đã cập nhật xong. Kiểm tra các giá trị có thể từng sai:")
print(df[df["NGAYDENHAN_clean"] == correct_date][["NGAYDENHAN", "NGAYDENHAN_clean"]].head())

import matplotlib.pyplot as plt
import seaborn as sns

# Chuyển datetime về dạng số (timestamp)
df["OPEN_DATE_NUM"] = df["OPEN_DATE_clean"].map(pd.Timestamp.toordinal)
df["NGAYDENHAN_NUM"] = df["NGAYDENHAN_clean"].map(pd.Timestamp.toordinal)

# Vẽ boxplot
plt.figure(figsize=(10, 5))

# OPEN_DATE
plt.subplot(1, 2, 1)
sns.boxplot(y=df["OPEN_DATE_NUM"])
plt.title("Boxplot - OPEN_DATE_clean")
plt.ylabel("Ngày (ordinal)")
plt.yticks(
    ticks=[int(df["OPEN_DATE_NUM"].min()), int(df["OPEN_DATE_NUM"].max())],
    labels=[df["OPEN_DATE_clean"].min().date(), df["OPEN_DATE_clean"].max().date()]
)

# NGAYDENHAN
plt.subplot(1, 2, 2)
sns.boxplot(y=df["NGAYDENHAN_NUM"])
plt.title("Boxplot - NGAYDENHAN_clean")
plt.ylabel("Ngày (ordinal)")
plt.yticks(
    ticks=[int(df["NGAYDENHAN_NUM"].min()), int(df["NGAYDENHAN_NUM"].max())],
    labels=[df["NGAYDENHAN_clean"].min().date(), df["NGAYDENHAN_clean"].max().date()]
)

plt.tight_layout()
plt.show()

#Trích xuất thành phần thời gian
df["OPEN_YEAR"] = df["OPEN_DATE_clean"].dt.year
df["OPEN_MONTH"] = df["OPEN_DATE_clean"].dt.month
df["OPEN_DAYOFWEEK"] = df["OPEN_DATE_clean"].dt.dayofweek  # 0 = Monday

# Tách năm, tháng, thứ trong tuần từ cột NGAYDENHAN_clean
df["DUE_YEAR"] = df["NGAYDENHAN_clean"].dt.year
df["DUE_MONTH"] = df["NGAYDENHAN_clean"].dt.month
df["DUE_DAYOFWEEK"] = df["NGAYDENHAN_clean"].dt.dayofweek  # 0 = Monday, 6 = Sunday

df.head()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

# 2. Chuẩn hóa giới tính
sex_mapping = {
    'ONG': 'MR', 'MR': 'MR',
    'BA': 'MRS', 'MRS': 'MRS', 'MS': 'MRS'
}
df['SEX'] = df['SEX'].map(sex_mapping).fillna('UNKNOWN')

# 3. Tạo biến target
df['target'] = df['NHOMNOMOI'].apply(lambda x: 1 if x == 1 else 0)

# 4. Tạo các biến thời gian từ ngày mở và ngày đến hạn
df["OPEN_YEAR"] = df["OPEN_DATE_clean"].dt.year
df["OPEN_MONTH"] = df["OPEN_DATE_clean"].dt.month
df["OPEN_DAYOFWEEK"] = df["OPEN_DATE_clean"].dt.dayofweek

df["DUE_YEAR"] = df["NGAYDENHAN_clean"].dt.year
df["DUE_MONTH"] = df["NGAYDENHAN_clean"].dt.month
df["DUE_DAYOFWEEK"] = df["NGAYDENHAN_clean"].dt.dayofweek

# 5. Bỏ các cột không cần
df_model = df.drop(columns=[
    'NHOMNOMOI',
    'OPEN_DATE', 'NGAYDENHAN',             # nếu có trong df
    'OPEN_DATE_clean', 'NGAYDENHAN_clean',  # đã sinh ra các biến thời gian rồi
    'OPEN_DATE_NUM',	'NGAYDENHAN_NUM'
])

# 6. Xác định các biến
numeric_cols = ['BASE_BAL', 'CURR_BAL', 'DUNO_QD', 'LAISUAT', 'OPEN_YEAR', 'DUE_YEAR']
categorical_cols = [col for col in df_model.columns if col not in numeric_cols + ['target']]

# 7. Chia dữ liệu thành train/test
X = df_model.drop(columns=['target'])
y = df_model['target']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# 8. Ép kiểu categorical về string cho cả train và test
for col in categorical_cols:
    X_train[col] = X_train[col].astype(str)
    X_test[col] = X_test[col].astype(str)

# 9. ColumnTransformer: chuẩn hóa và one-hot encode
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
    ]
)

# 10. Fit và transform dữ liệu
X_train_enc = preprocessor.fit_transform(X_train)
X_test_enc = preprocessor.transform(X_test)

# 11. In kết quả
print("Categorical columns:", categorical_cols)
print("Numeric columns:", numeric_cols)
print("Kích thước tập train sau biến đổi:", X_train_enc.shape)
print("Kích thước tập test sau biến đổi:", X_test_enc.shape)

df_model.head()

# Hiển thị tối đa tất cả cột
pd.set_option('display.max_columns', None)

# (Tùy chọn) Hiển thị tối đa nhiều dòng hơn nếu bạn cần
pd.set_option('display.max_rows', 100)

# (Tùy chọn) Mở rộng chiều rộng màn hình hiển thị
pd.set_option('display.width', None)

# (Tùy chọn) Không cắt nội dung trong mỗi ô
pd.set_option('display.max_colwidth', None)
df_model.head()

#Xem tỷ lệ unbalance của biến target
print("🔍 Phân bố lớp target:")
print(df["target"].value_counts())
print("\n📊 Tỷ lệ phần trăm mỗi lớp:")
print(df["target"].value_counts(normalize=True).round(4) * 100)
import matplotlib.pyplot as plt
import seaborn as sns

sns.countplot(data=df, x="target")
plt.title("Phân bố biến target (good vs bad)")
plt.xlabel("Target (0 = bad, 1 = good)")
plt.ylabel("Số lượng")
plt.show()

"""✅ Bước 1: Sao chép df_model để xử lý riêng"""

df_work = df_model.copy()

"""✅ Bước 2: Xác định lại các biến
python


"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

# Danh sách numeric và categorical
numeric_cols = ['BASE_BAL', 'CURR_BAL', 'DUNO_QD', 'LAISUAT', 'OPEN_YEAR', 'DUE_YEAR']
categorical_cols = [col for col in df_work.columns if col not in numeric_cols + ['target']]

# Tách X/y
X = df_work.drop(columns=["target"])
y = df_work["target"]

# Tách train/test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# Ép kiểu categorical
for col in categorical_cols:
    X_train[col] = X_train[col].astype(str)
    X_test[col] = X_test[col].astype(str)

#✅ Bước 3: Encode với ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
    ]
)

# Fit + transform
X_train_enc = preprocessor.fit_transform(X_train)
X_test_enc = preprocessor.transform(X_test)

from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train_enc, y_train)


#4 ✅ Bước 4: Áp dụng SMOTE và lưu vào biến mới
# In xác nhận
from collections import Counter
print("✅ SMOTE applied. Class distribution:")
print(Counter(y_train_smote))

#Logistic model
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
import pandas as pd

# 1. Khởi tạo và huấn luyện mô hình Logistic Regression
log_model = LogisticRegression(class_weight="balanced",max_iter=1000, random_state=42)
log_model.fit(X_train_smote, y_train_smote)

# 2. Dự đoán trên tập kiểm tra
y_pred_log = log_model.predict(X_test_enc)
y_proba_log = log_model.predict_proba(X_test_enc)[:, 1]  # Xác suất cho class "good"

# 3. In báo cáo classification
print("🔍 Classification Report:")
print(classification_report(y_test, y_pred_log, target_names=["bad", "good"]))

# 4. In confusion matrix
print("\n📊 Confusion Matrix:")
print(pd.DataFrame(
    confusion_matrix(y_test, y_pred_log),
    index=["Actual: bad", "Actual: good"],
    columns=["Predicted: bad", "Predicted: good"]
))

# 5. Tính AUC
auc_score = roc_auc_score(y_test, y_proba_log)
print(f"\n🎯 ROC AUC Score: {auc_score:.4f}")

# 6. Vẽ Confusion Matrix bằng heatmap
import seaborn as sns
import matplotlib.pyplot as plt

conf_matrix = confusion_matrix(y_test, y_pred_log)

plt.figure(figsize=(6, 4))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues',
            xticklabels=["Predicted: bad", "Predicted: good"],
            yticklabels=["Actual: bad", "Actual: good"])
plt.title("🔍 Confusion Matrix – Logistic Regression")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.tight_layout()
plt.show()

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

# Khai báo các tham số cần dò tìm
param_grid = {
    'C': [0.1, 1],
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear']
}

# Tìm mô hình Logistic Regression tối ưu theo F1-score
grid = GridSearchCV(
    LogisticRegression(max_iter=1000, random_state=42),
    param_grid,
    cv=3,
    scoring='f1',
    n_jobs=-1  # sử dụng toàn bộ CPU để tăng tốc
)

# Fit mô hình trên dữ liệu đã qua SMOTE
grid.fit(X_train_smote, y_train_smote)

from sklearn.metrics import classification_report, confusion_matrix, f1_score, roc_auc_score
import pandas as pd

# 1. In tham số tốt nhất và F1 trên cross-validation
print("✅ Best Parameters:", grid.best_params_)
print(f"✅ Best Cross-Validated F1 Score: {grid.best_score_:.4f}")

# 2. Lấy mô hình tốt nhất
best_model = grid.best_estimator_

# 3. Dự đoán trên tập test
y_pred_best = best_model.predict(X_test_enc)
y_proba_best = best_model.predict_proba(X_test_enc)[:, 1]

# 4. Đánh giá mô hình
print("\n📊 Classification Report (Test Set):")
print(classification_report(y_test, y_pred_best, target_names=["bad", "good"]))

print("📉 Confusion Matrix:")
print(pd.DataFrame(
    confusion_matrix(y_test, y_pred_best),
    index=["Actual: bad", "Actual: good"],
    columns=["Predicted: bad", "Predicted: good"]
))

# 5. F1 và AUC
f1 = f1_score(y_test, y_pred_best)
auc = roc_auc_score(y_test, y_proba_best)
print(f"\n🎯 Test F1 Score: {f1:.4f}")
print(f"🎯 Test ROC AUC Score: {auc:.4f}")

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
import pandas as pd

# Khởi tạo và huấn luyện mô hình
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train_smote, y_train_smote)

# Dự đoán xác suất
y_proba_rf = rf_model.predict_proba(X_test_enc)[:, 1]

# === Chọn ngưỡng (threshold) tùy chỉnh ===
threshold = 0.7  # Thử các giá trị như 0.3, 0.4, 0.45 để tăng recall cho bad
y_pred_rf_thresh = (y_proba_rf >= threshold).astype(int)

# Đánh giá mô hình tại threshold mới
print(f"\n📊 Classification Report tại threshold = {threshold}:")
print(classification_report(y_test, y_pred_rf_thresh, target_names=["bad", "good"]))

print("\n📉 Confusion Matrix:")
print(pd.DataFrame(confusion_matrix(y_test, y_pred_rf_thresh),
                   index=["Actual: bad", "Actual: good"],
                   columns=["Predicted: bad", "Predicted: good"]))

print(f"🎯 ROC AUC Score: {roc_auc_score(y_test, y_proba_rf):.4f}")

import matplotlib.pyplot as plt
import seaborn as sns

# Tính confusion matrix
cm = confusion_matrix(y_test, y_pred_rf_thresh)
labels = ["Bad", "Good"]

# Vẽ heatmap cho confusion matrix
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title(f"Confusion Matrix - Random forest ")
plt.tight_layout()
plt.show()

#Tối ưu threshold phân loại
import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score

# Xác suất dự đoán class 1 (good)
y_scores_rf = rf_model.predict_proba(X_test_enc)[:, 1]

# Thử nhiều ngưỡng
thresholds = np.arange(0.0, 1.01, 0.01)
recalls = []
precisions = []
f1s = []

for t in thresholds:
    y_pred_thresh = (y_scores_rf >= t).astype(int)
    recalls.append(recall_score(y_test, y_pred_thresh))
    precisions.append(precision_score(y_test, y_pred_thresh))
    f1s.append(f1_score(y_test, y_pred_thresh))

import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
plt.plot(thresholds, recalls, label='Recall')
plt.plot(thresholds, precisions, label='Precision')
plt.plot(thresholds, f1s, label='F1 Score')
plt.xlabel('Threshold')
plt.ylabel('Score')
plt.title('Threshold vs Recall / Precision / F1 (Random Forest)')
plt.legend()
plt.grid()
plt.show()

# Ngưỡng tốt nhất theo F1
best_t = thresholds[np.argmax(f1s)]
print(f"✅ Ngưỡng tối ưu theo F1: {best_t:.2f}")

#Đánh giá mô hình tại threshold =0.7
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
import pandas as pd

# Dự đoán lại theo ngưỡng mới
y_pred_thresh_rf = (y_scores_rf >= 0.7).astype(int)

# 📊 In classification report
print("📍 Classification Report tại threshold = 0.")
print(classification_report(y_test, y_pred_thresh_rf, target_names=["bad", "good"]))

# 📉 Confusion matrix
print("Confusion Matrix:")
print(pd.DataFrame(confusion_matrix(y_test, y_pred_thresh_rf),
                   index=["Actual: bad", "Actual: good"],
                   columns=["Predicted: bad", "Predicted: good"]))

# 🎯 AUC Score (vẫn dùng xác suất)
auc = roc_auc_score(y_test, y_scores_rf)
print(f"\n🎯 ROC AUC Score: {auc:.4f}")

#XGboost
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
import pandas as pd

# 1. Khởi tạo và huấn luyện mô hình XGBoost
xgb_model = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)
xgb_model.fit(X_train_smote, y_train_smote)

# 2. Dự đoán trên tập kiểm tra
y_pred_xgb = xgb_model.predict(X_test_enc)
y_proba_xgb = xgb_model.predict_proba(X_test_enc)[:, 1]  # Xác suất cho class "good"

# 3. In báo cáo classification
print("📊 XGBoost – Classification Report:")
print(classification_report(y_test, y_pred_xgb, target_names=["bad", "good"]))

# 4. Confusion Matrix
print("\n📉 Confusion Matrix:")
print(pd.DataFrame(
    confusion_matrix(y_test, y_pred_xgb),
    index=["Actual: bad", "Actual: good"],
    columns=["Predicted: bad", "Predicted: good"]
))

# 5. ROC AUC Score
auc_score = roc_auc_score(y_test, y_proba_xgb)
print(f"\n🎯 ROC AUC Score: {auc_score:.4f}")

# === Thay đổi ngưỡng threshold tùy chỉnh ===
threshold = 0.7  # Bạn có thể thử 0.3, 0.4, 0.5, ..., 0.9 để tìm giá trị phù hợp
y_pred_xgb_thresh = (y_proba_xgb >= threshold).astype(int)

# === Đánh giá mô hình tại threshold mới ===
print(f"\n📊 Classification Report tại threshold = {threshold}:")
print(classification_report(y_test, y_pred_xgb_thresh, target_names=["bad", "good"]))

print("\n📉 Confusion Matrix:")
print(pd.DataFrame(
    confusion_matrix(y_test, y_pred_xgb_thresh),
    index=["Actual: bad", "Actual: good"],
    columns=["Predicted: bad", "Predicted: good"]
))

print(f"🎯 ROC AUC Score (không đổi): {roc_auc_score(y_test, y_proba_xgb):.4f}")

# === Vẽ Confusion Matrix tại threshold mới ===
cm_xgb_thresh = confusion_matrix(y_test, y_pred_xgb_thresh)
labels = ["Bad", "Good"]

plt.figure(figsize=(6, 4))
sns.heatmap(cm_xgb_thresh, annot=True, fmt='d', cmap='Oranges', xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title(f"XGBoost – Confusion Matrix (Threshold = {threshold})")
plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import precision_score, recall_score, f1_score

# Lấy xác suất dự đoán cho class "good"
y_scores = xgb_model.predict_proba(X_test_enc)[:, 1]

# Lặp qua các threshold từ 0.0 đến 1.0
thresholds = np.arange(0.0, 1.01, 0.01)
precisions, recalls, f1s = [], [], []

for t in thresholds:
    y_pred_thresh = (y_scores >= t).astype(int)
    precisions.append(precision_score(y_test, y_pred_thresh))
    recalls.append(recall_score(y_test, y_pred_thresh))
    f1s.append(f1_score(y_test, y_pred_thresh))

# Vẽ biểu đồ
plt.figure(figsize=(10, 6))
plt.plot(thresholds, precisions, label='Precision')
plt.plot(thresholds, recalls, label='Recall')
plt.plot(thresholds, f1s, label='F1 Score')
plt.axvline(x=0.5, color='gray', linestyle='--', label='Default threshold (0.5)')
plt.xlabel('Threshold')
plt.ylabel('Score')
plt.title('Precision, Recall, F1 Score vs Threshold (XGBoost)')
plt.legend()
plt.grid()
plt.show()

# In ngưỡng tối ưu theo F1 hoặc bạn có thể chọn theo Recall
best_threshold = thresholds[np.argmax(f1s)]
print(f"✅ Ngưỡng tối ưu theo F1 Score: {best_threshold:.2f}")

y_pred_best = (y_scores >= best_threshold).astype(int)
print(classification_report(y_test, y_pred_best, target_names=["bad", "good"]))

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import pandas as pd

# Đảm bảo bạn đã có các biến:
# y_test, y_pred_log, y_proba_log
# y_pred_rf, y_proba_rf
# y_pred_xgb, y_proba_xgb

# Hàm tính các chỉ số đánh giá
def evaluate_model(name, y_true, y_pred, y_proba):
    return {
        'Model': name,
        'Accuracy': accuracy_score(y_true, y_pred),
        'Precision': precision_score(y_true, y_pred),
        'Recall': recall_score(y_true, y_pred,pos_label=0),
        'F1 Score': f1_score(y_true, y_pred),
        'ROC AUC': roc_auc_score(y_true, y_proba)
    }

# Gộp kết quả của 3 mô hình
results = [
    evaluate_model("Logistic Regression", y_test, y_pred_log, y_proba_log),
    evaluate_model("Random Forest", y_test, y_pred_rf_thresh, y_proba_rf),
    evaluate_model("XGBoost", y_test, y_pred_xgb, y_proba_xgb)
]

# Tạo bảng so sánh
df_results = pd.DataFrame(results)
df_results.set_index('Model', inplace=True)

# Hiển thị kết quả
print("🔍 So sánh hiệu suất 3 mô hình:")
display(df_results.round(4))

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

# Tính toán FPR và TPR cho từng mô hình
fpr_log, tpr_log, _ = roc_curve(y_test, y_proba_log)
fpr_rf, tpr_rf, _ = roc_curve(y_test, y_proba_rf)
fpr_xgb, tpr_xgb, _ = roc_curve(y_test, y_proba_xgb)

# Tính AUC cho từng mô hình
auc_log = auc(fpr_log, tpr_log)
auc_rf = auc(fpr_rf, tpr_rf)
auc_xgb = auc(fpr_xgb, tpr_xgb)

# Vẽ biểu đồ
plt.figure(figsize=(8, 6))
plt.plot(fpr_log, tpr_log, label=f'Logistic Regression (AUC = {auc_log:.4f})')
plt.plot(fpr_rf, tpr_rf, label=f'Random Forest (AUC = {auc_rf:.4f})')
plt.plot(fpr_xgb, tpr_xgb, label=f'XGBoost (AUC = {auc_xgb:.4f})')

# Đường tham chiếu
plt.plot([0, 1], [0, 1], 'k--', label='Random Guess')

# Tùy chỉnh đồ họa
plt.title('🎯 ROC Curve So sánh 3 mô hình')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.legend(loc='lower right')
plt.grid(True)
plt.tight_layout()
plt.show()



# Upload CSV file from local system
from google.colab import files
uploaded = files.upload()

import pandas as pd

# Đọc dữ liệu từ file Excel
df_new = pd.read_excel('Data-Validation.xlsx')  # Thay bằng đường dẫn file thực tế



df_new.head()

# 1. Chuẩn hóa cột SEX
sex_mapping = {
    'ONG': 'MR', 'MR': 'MR',
    'BA': 'MRS', 'MRS': 'MRS', 'MS': 'MRS'
}
df_new['SEX'] = df_new['SEX'].map(sex_mapping).fillna('UNKNOWN')

df_new['SEX'].unique()

# Copy lại để xử lý
df_new["OPEN_DATE_clean"] = pd.NaT

# Với các dòng có giá trị là số (serial date)
mask_numeric = df_new["OPEN_DATE"].apply(lambda x: str(x).replace('.', '').isnumeric())

# Dòng là chuỗi ngày hợp lệ
mask_string = ~mask_numeric

# Áp dụng chuyển đổi với từng loại
# Fix: Apply the mask_numeric to df_new, not df
df_new.loc[mask_numeric, "OPEN_DATE_clean"] = pd.to_datetime(df_new.loc[mask_numeric, "OPEN_DATE"].astype(float),
                                                         origin="1899-12-30", unit="D", errors="coerce")

# Apply the mask_string to df_new
df_new.loc[mask_string, "OPEN_DATE_clean"] = pd.to_datetime(df_new.loc[mask_string, "OPEN_DATE"],
                                                        format="%d/%m/%Y", errors="coerce")

# Kiểm tra kết quả
print(df_new[["OPEN_DATE", "OPEN_DATE_clean"]].head())

# Tạo cột clean mặc định là NaT
df_new["NGAYDENHAN_clean"] = pd.NaT

# Mask số: kiểm tra nếu là số serial Excel
mask_numeric_ngay = df_new["NGAYDENHAN"].apply(lambda x: str(x).replace('.', '').isnumeric())

# Còn lại là chuỗi ngày (mask ngược lại)
mask_string_ngay = ~mask_numeric_ngay

# Chuyển đổi giá trị kiểu số (serial Excel)
df_new.loc[mask_numeric_ngay, "NGAYDENHAN_clean"] = pd.to_datetime(
    df_new.loc[mask_numeric_ngay, "NGAYDENHAN"].astype(float),
    origin="1899-12-30", unit="D", errors="coerce"
)

# Chuyển đổi giá trị kiểu chuỗi
df_new.loc[mask_string_ngay, "NGAYDENHAN_clean"] = pd.to_datetime(
    df_new.loc[mask_string_ngay, "NGAYDENHAN"],
    format="%d/%m/%Y", errors="coerce"
)
# Kiểm tra kết quả
print(df_new[["NGAYDENHAN", "NGAYDENHAN_clean"]].head())

# Tạo mask kiểm tra lỗi ở cả 2 cột
invalid_mask = df_new["OPEN_DATE_clean"].isna() | df_new["NGAYDENHAN_clean"].isna()

# Lọc các dòng có lỗi
invalid_rows = df_new[invalid_mask]

# Đếm số lỗi
num_invalid = invalid_rows.shape[0]
print(f"🛑 Số lượng dòng có lỗi trong OPEN_DATE_clean hoặc NGAYDENHAN_clean: {num_invalid}")

# Hiển thị một số ví dụ lỗi gốc
if num_invalid > 0:
    print("📋 Một số giá trị gốc bị lỗi khi chuyển datetime:")
    display(invalid_rows[["OPEN_DATE", "NGAYDENHAN"]].drop_duplicates().head(10))
else:
    print("✅ Không có lỗi nào trong OPEN_DATE_clean hoặc NGAYDENHAN_clean — tất cả đã chuyển đổi thành datetime thành công.")

df_new.head()

#Trích xuất thành phần thời gian
df_new["OPEN_YEAR"] = df_new["OPEN_DATE_clean"].dt.year
df_new["OPEN_MONTH"] = df_new["OPEN_DATE_clean"].dt.month
df_new["OPEN_DAYOFWEEK"] = df_new["OPEN_DATE_clean"].dt.dayofweek  # 0 = Monday
# Tách năm, tháng, thứ trong tuần từ cột NGAYDENHAN_clean
df_new["DUE_YEAR"] = df_new["NGAYDENHAN_clean"].dt.year
df_new["DUE_MONTH"] = df_new["NGAYDENHAN_clean"].dt.month
df_new["DUE_DAYOFWEEK"] = df_new["NGAYDENHAN_clean"].dt.dayofweek  # 0 = Monday, 6 = Sunday

df_new.head()

# Bỏ các cột không dùng
selected_columns = [
    'PHUONG THUC CHO VAY', 'LOAIKH', 'SEX', 'CURRENCYCD', 'DESC_TIME',
    'MJACCTTYPDESC', 'ORGNAME', 'PARENTORGNAME', 'MUCDICHVAY',
    'BASE_BAL', 'CURR_BAL', 'DUNO_QD', 'LAISUAT',
    "OPEN_YEAR", "OPEN_MONTH", "OPEN_DAYOFWEEK",
    "DUE_YEAR", "DUE_MONTH", "DUE_DAYOFWEEK"
]

df_new_model = df_new[selected_columns].copy()

# Chỉ ép kiểu string cho các cột categorical có tồn tại trong df_new_model
for col in categorical_cols:
    if col in df_new_model.columns:
        df_new_model[col] = df_new_model[col].astype(str)

# Encode dữ liệu mới (dùng preprocessor đã được fit từ trước)
X_new_enc = preprocessor.transform(df_new_model)

df_new_model.head()

threshold = 0.7
df_new['predicted_target_rf_thresh'] = (df_new['proba_rf'] >= threshold).astype(int)
df_new['predicted_label_rf_thresh'] = df_new['predicted_target_rf_thresh'].map({1: 'Good', 0: 'Bad'})

df_new.head()

print(df_new['predicted_label_rf_thresh'].value_counts())

# Lọc các dòng có proba_rf > 0.7
filtered_df = df_new[df_new['proba_rf'] > 0.7]

# Lấy các giá trị unique trong cột predicted_label_rf_thresh
unique_labels = filtered_df['predicted_label_rf_thresh'].unique()

print("Các giá trị unique của predicted_label_rf_thresh khi proba_rf > 0.7:")
print(unique_labels)

df_new.to_excel("du_lieu_du_doan_threshold_rf.xlsx", index=False)
print("✅ File đã được lưu thành công.")

from google.colab import files
files.download("du_lieu_du_doan_threshold_rf.xlsx")



"""=====================================
Cũ
"""

