# -*- coding: utf-8 -*-
"""Đánh giá tín dụng_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XuhHaU7lfkrdIX1J2ARIR65FA6nUVzxB
"""

# Upload CSV file from local system
from google.colab import files
uploaded = files.upload()

# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_auc_score, roc_curve
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

df_raw = pd.read_excel("Data_For Midterm and Final Project.xlsx")
df = df_raw.copy()
selected_columns = [
    'PHUONG THUC CHO VAY', 'LOAIKH', 'SEX', 'CURRENCYCD', 'DESC_TIME',
    'MJACCTTYPDESC', 'ORGNAME', 'PARENTORGNAME', 'MUCDICHVAY',
    'BASE_BAL', 'CURR_BAL', 'DUNO_QD', 'LAISUAT',"NHOMNOMOI"
]

# Lọc dataframe
df = df[selected_columns]

pd.set_option('display.max_columns', None)   # Hiện tất cả các cột
pd.set_option('display.width', None)         # Không giới hạn độ rộng dòng
pd.set_option('display.max_colwidth', None)  # Hiện toàn bộ nội dung trong mỗi cột

# Xem dữ liệu
print(df.head())

# Bước 2: Kiểm tra tổng số giá trị bị thiếu ở mỗi cột
print("🔎 Missing values per column:")
missing_per_column = df.isnull().sum()
print(missing_per_column[missing_per_column > 0])

# Bước 3: Kiểm tra và hiển thị các dòng bị thiếu
missing_rows = df[df.isnull().any(axis=1)]
num_missing_rows = missing_rows.shape[0]

print(f"\n📌 Total rows with missing values: {num_missing_rows}")

# Bước 4: Hiển thị bảng các dòng bị thiếu
if num_missing_rows > 0:
    print("\n📋 Rows with missing values:")
    print(missing_rows)
else:
    print("✅ No rows with missing values found.")

# Tính tỷ lệ thiếu dữ liệu của cột 'SEX'
missing_ratio_sex = df['SEX'].isnull().mean() * 100

print(f"Tỷ lệ thiếu của cột 'SEX': {missing_ratio_sex:.2f}%")

# Mapping giá trị SEX
sex_mapping = {
    'ONG': 'MR',
    'MR': 'MR',
    'BA': 'MRS',
    'MRS': 'MRS',
    'MS': 'MRS'
}

# Mapping giá trị SEX
sex_mapping = {
    'ONG': 'MR',
    'MR': 'MR',
    'BA': 'MRS',
    'MRS': 'MRS',
    'MS': 'MRS'
}

# Thay đổi giá trị theo mapping, giữ NaN
df['SEX'] = df['SEX'].map(sex_mapping).fillna('UNKNOWN')
# In ra các giá trị unique của cột 'SEX' sau khi xử lý
print(df['SEX'].unique())

# Tính tần suất và phần trăm
sex_counts = df['SEX'].value_counts()
sex_percent = sex_counts / sex_counts.sum() * 100

# Tạo biểu đồ 2 trong 1
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# 🎯 Biểu đồ cột
sns.countplot(ax=axes[0], data=df, x='SEX', order=sex_counts.index)
axes[0].set_title('Số lượng khách hàng theo giới tính')
axes[0].set_xlabel('Giới tính')
axes[0].set_ylabel('Số lượng')

# 🥧 Biểu đồ tròn
axes[1].pie(sex_percent, labels=sex_percent.index, autopct='%1.1f%%', startangle=90)
axes[1].set_title('Tỷ lệ phần trăm giới tính')

plt.tight_layout()
plt.show()

categorical_cols = [
    'PHUONG THUC CHO VAY', 'LOAIKH', 'SEX', 'CURRENCYCD',
    'DESC_TIME', 'MJACCTTYPDESC', 'ORGNAME', 'PARENTORGNAME', 'MUCDICHVAY'
]

# Khởi tạo danh sách kết quả
summary_data = []

# Duyệt qua từng cột và lưu từng giá trị + số lượng
for col in categorical_cols:
    value_counts = df[col].value_counts(dropna=False)
    for category, count in value_counts.items():
        summary_data.append({
            'Tên biến': col,
            'Giá trị category': category,
            'Số lượng': count
        })

# Tạo bảng kết quả
summary_df = pd.DataFrame(summary_data)

# Hiển thị bảng trong Colab
from IPython.display import display
display(summary_df)

from matplotlib.colors import LogNorm

cols = ['PHUONG THUC CHO VAY', 'PARENTORGNAME', 'MUCDICHVAY']

for i in range(len(cols)):
    for j in range(i+1, len(cols)):
        col1 = cols[i]
        col2 = cols[j]

        ct = pd.crosstab(df[col1], df[col2])

        # Ẩn các ô có giá trị nhỏ để không làm rối heatmap
        annot_data = ct.copy().astype(str)
        annot_data[ct < 5] = ""

        plt.figure(figsize=(20, 10))
        sns.heatmap(
            ct,
            cmap='YlGnBu',
            annot=annot_data,
            fmt='s',
            linewidths=0.5,
            norm=LogNorm()
        )
        plt.title(f"Heatmap giữa {col1} và {col2}", fontsize=14)
        plt.xlabel(col2, fontsize=12)
        plt.ylabel(col1, fontsize=12)
        plt.xticks(rotation=90, fontsize=8)
        plt.yticks(rotation=0, fontsize=8)
        plt.tight_layout()
        plt.show()

# Danh sách các cột cần vẽ pie chart
cols = ['LOAIKH', 'SEX', 'CURRENCYCD', 'MJACCTTYPDESC', 'MUCDICHVAY', "DESC_TIME"]

for col in cols:
    counts = df[col].value_counts(dropna=False)

    # Tạo biểu đồ
    plt.figure(figsize=(6, 6))
    plt.pie(
        counts,
        labels=counts.index.astype(str),
        autopct='%1.1f%%',
        startangle=90,
        counterclock=False
    )
    plt.title(f'Phân bố {col}', fontsize=14)
    plt.axis('equal')  # Đảm bảo hình tròn không bị méo
    plt.tight_layout()
    plt.show()

# Tạo bảng chéo đếm số lượng giao dịch giữa 2 biến
ct = pd.crosstab(df['MJACCTTYPDESC'], df['MUCDICHVAY'])

# Tùy chọn: ẩn các ô quá nhỏ để không rối
annot_data = ct.copy().astype(str)
annot_data[ct < 5] = ""

# Vẽ heatmap
plt.figure(figsize=(18, 8))
sns.heatmap(
    ct,
    cmap='YlGnBu',
    annot=annot_data,
    fmt='s',
    linewidths=0.7,
    annot_kws={'size': 4},
    norm=LogNorm()  # Giúp tăng tương phản nếu số lượng chênh lệch lớn
)
plt.title("Heatmap giữa MJACCTTYPDESC và MUCDICHVAY", fontsize=14)
plt.xlabel("MUCDICHVAY", fontsize=12)
plt.ylabel("MJACCTTYPDESC", fontsize=12)
plt.xticks(rotation=90, fontsize=8)
plt.yticks(rotation=0, fontsize=8)
plt.tight_layout()
plt.show()

df[['BASE_BAL', 'CURR_BAL', 'DUNO_QD', 'LAISUAT']].describe()

import seaborn as sns
import matplotlib.pyplot as plt

for col in ['BASE_BAL', 'CURR_BAL', 'DUNO_QD', 'LAISUAT']:
    plt.figure(figsize=(6, 3))
    sns.histplot(df[col], kde=True, bins=50)
    plt.title(f'Phân phối của {col}')
    plt.xlabel(col)
    plt.ylabel('Tần suất')
    plt.tight_layout()
    plt.show()

for col in ['BASE_BAL', 'CURR_BAL', 'DUNO_QD', 'LAISUAT']:
    plt.figure(figsize=(6, 2))
    sns.boxplot(x=df[col])
    plt.title(f'Boxplot của {col}')
    plt.tight_layout()
    plt.show()

df[['BASE_BAL', 'CURR_BAL', 'DUNO_QD', 'LAISUAT']].corr()

df['target'] = df['NHOMNOMOI'].apply(lambda x: 1 if x > 1 else 0)

for col in ['BASE_BAL', 'CURR_BAL', 'DUNO_QD', 'LAISUAT']:
    plt.figure(figsize=(6, 3))
    sns.boxplot(data=df, x='target', y=col)
    plt.title(f'{col} theo nhóm nợ (Good = 0 / Bad = 1)')
    plt.tight_layout()
    plt.show()

df['CURR_BAL_log'] = np.log1p(df['CURR_BAL'])  # log(1 + x)
bins = [0, 5e7, 2e8, 1e9, 1e11]  # có thể điều chỉnh tùy theo phân phối
labels = ['Nhỏ', 'Vừa', 'Lớn', 'Rất lớn']
df['CURR_BAL_group'] = pd.cut(df['CURR_BAL'], bins=bins, labels=labels)

df['target'] = df['NHOMNOMOI'].apply(lambda x: 0 if x > 1 else 1)  # 1 = Good

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(6, 3))
sns.boxplot(data=df, x='target', y='CURR_BAL_log')
plt.title('CURR_BAL (log) theo nhóm nợ (0=Good, 1=Bad)')
plt.xlabel('Nhóm nợ')
plt.ylabel('log(CURR_BAL)')
plt.tight_layout()
plt.show()

df['CURR_BAL_group'].value_counts()

df.head()

# 1. Cài đặt thư viện nếu cần
!pip install imbalanced-learn

# 2. Import thư viện
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

from imblearn.over_sampling import SMOTE

# 3. Chọn cột
selected_columns = [
    'PHUONG THUC CHO VAY', 'LOAIKH', 'SEX', 'CURRENCYCD', 'DESC_TIME',
    'MJACCTTYPDESC', 'ORGNAME', 'PARENTORGNAME', 'MUCDICHVAY',
    'BASE_BAL', 'CURR_BAL', 'DUNO_QD', 'LAISUAT', 'NHOMNOMOI'
]
df = df[selected_columns].copy()

# 4. Chuẩn hóa giới tính
sex_mapping = {
    'ONG': 'MR', 'MR': 'MR',
    'BA': 'MRS', 'MRS': 'MRS', 'MS': 'MRS'
}
df['SEX'] = df['SEX'].map(sex_mapping).fillna('UNKNOWN')

# 5. Tạo biến target
df['target'] = df['NHOMNOMOI'].apply(lambda x: 1 if x == 1 else 0)

# 6. Bỏ cột không cần
df_model = df.drop(columns=['NHOMNOMOI'])

# 7. Tách X và y
X = df_model.drop(columns=['target'])
y = df_model['target']

# 8. Xác định categorical và numerical rõ ràng
numerical_cols = ['BASE_BAL', 'CURR_BAL', 'DUNO_QD', 'LAISUAT']
categorical_cols = [col for col in X.columns if col not in numerical_cols]

# 9. Chuyển categorical sang dạng chuỗi (để encode)
for col in categorical_cols:
    X[col] = X[col].astype(str)

# 10. Tiền xử lý
preprocessor = ColumnTransformer([
    ('num', StandardScaler(), numerical_cols),
    ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
])

# 11. Tách train/test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# 12. Xử lý trước khi SMOTE
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

# 13. SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_train_processed, y_train)

# 14. Huấn luyện mô hình
model = LogisticRegression(solver='liblinear')
model.fit(X_resampled, y_resampled)

# 15. Dự đoán
y_pred = model.predict(X_test_processed)

# 16. Đánh giá mô hình
print("Classification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
cm = confusion_matrix(y_test, y_pred)
ConfusionMatrixDisplay(confusion_matrix=cm).plot(cmap='Blues')
plt.title("Confusion Matrix (SMOTE + Logistic Regression)")
plt.show()

# 1. Import thư viện
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

# 2. Chọn các cột cần dùng
selected_columns = [
    'PHUONG THUC CHO VAY', 'LOAIKH', 'SEX', 'CURRENCYCD', 'DESC_TIME',
    'MJACCTTYPDESC', 'ORGNAME', 'PARENTORGNAME', 'MUCDICHVAY',
    'BASE_BAL', 'CURR_BAL', 'DUNO_QD', 'LAISUAT', 'NHOMNOMOI'
]
df = df[selected_columns].copy()

# 3. Chuẩn hóa giới tính
sex_mapping = {
    'ONG': 'MR', 'MR': 'MR',
    'BA': 'MRS', 'MRS': 'MRS', 'MS': 'MRS'
}
df['SEX'] = df['SEX'].map(sex_mapping).fillna('UNKNOWN')

# 4. Tạo biến target: 1 = Good (nhóm 1), 0 = Bad
df['target'] = df['NHOMNOMOI'].apply(lambda x: 1 if x == 1 else 0)

# 5. Bỏ cột không cần
df_model = df.drop(columns=['NHOMNOMOI'])

# 6. Tách X và y
X = df_model.drop(columns=['target'])
y = df_model['target']

# 7. Xác định rõ các cột
numerical_cols = ['BASE_BAL', 'CURR_BAL', 'DUNO_QD', 'LAISUAT']
categorical_cols = [col for col in X.columns if col not in numerical_cols]

# 8. Chuyển toàn bộ categorical thành string
for col in categorical_cols:
    X[col] = X[col].astype(str)

# 9. Tiền xử lý
preprocessor = ColumnTransformer([
    ('num', StandardScaler(), numerical_cols),
    ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
])

# 10. Pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(solver='liblinear'))
])

# 11. Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# 12. Huấn luyện mô hình
pipeline.fit(X_train, y_train)

# 13. Dự đoán và đánh giá
y_pred = pipeline.predict(X_test)

print("Classification Report:\n", classification_report(y_test, y_pred))

# 14. Ma trận nhầm lẫn
print("\nConfusion Matrix:")
cm = confusion_matrix(y_test, y_pred)
ConfusionMatrixDisplay(confusion_matrix=cm).plot(cmap='Blues')
plt.title("Confusion Matrix - Logistic Regression (No SMOTE)")
plt.show()



df.head()

df.head()

df_model

# 1. Import thư viện
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

# 2. Bỏ các cột không cần
df_model = df.drop(columns=['CURR_BAL_log', 'CURR_BAL_group', 'NHOMNOMOI'])

# 3. X và y
X = df_model.drop(columns=['target'])
y = df_model['target']

# 4. Undersampling
# Tìm số mẫu tối thiểu giữa 2 lớp
count_class_0, count_class_1 = y.value_counts()

# Tách các nhóm
df_0 = df_model[df_model['target'] == 0].copy() # Add .copy() to avoid SettingWithCopyWarning
df_1 = df_model[df_model['target'] == 1].copy() # Add .copy() to avoid SettingWithCopyWarning

# Undersample lớp nhiều hơn
if count_class_0 > count_class_1:
    df_0_under = df_0.sample(count_class_1, random_state=42)
    df_balanced = pd.concat([df_0_under, df_1])
else:
    df_1_under = df_1.sample(count_class_0, random_state=42)
    df_balanced = pd.concat([df_1_under, df_0])

# Reset lại chỉ số
df_balanced = df_balanced.sample(frac=1, random_state=42).reset_index(drop=True)

# 5. Chia lại X, y sau khi cân bằng
X = df_balanced.drop(columns=['target'])
y = df_balanced['target']

# 6. Xác định cột dạng số và phân loại
categorical_cols = X.select_dtypes(include='object').columns.tolist()
numerical_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()

# Convert all categorical columns to string type to ensure uniformity
# This is the fix for the TypeError
for col in categorical_cols:
    X[col] = X[col].astype(str)

# Re-identify categorical and numerical columns after conversion
# (This step is optional here as we converted to string, but good practice if dtypes might genuinely change)
categorical_cols = X.select_dtypes(include='object').columns.tolist()
numerical_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()


# 7. Tạo pipeline
preprocessor = ColumnTransformer([
    ('num', StandardScaler(), numerical_cols),
    # Use handle_unknown='ignore' to handle unseen categories in test set
    ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
])

pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(solver='liblinear'))
])

# 8. Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

# 9. Huấn luyện
pipeline.fit(X_train, y_train)

# 10. Dự đoán
y_pred = pipeline.predict(X_test)

# 11. Đánh giá
print("Classification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
cm = confusion_matrix(y_test, y_pred)
ConfusionMatrixDisplay(cm).plot(cmap='Blues')
plt.show() # Add plt.show() to display the plot

def undersample_dataframe(df, target_col='target', random_state=42):
    """
    Thực hiện undersampling để cân bằng giữa các lớp trong cột target.
    Trả về dataframe đã được undersample.

    Parameters:
        df (pd.DataFrame): Dữ liệu đầu vào
        target_col (str): Tên cột nhãn (label)
        random_state (int): Seed cho reproducibility

    Returns:
        pd.DataFrame: Dữ liệu đã được cân bằng
    """
    # Đếm số mẫu mỗi lớp
    class_counts = df[target_col].value_counts()
    min_class = class_counts.idxmin()
    min_count = class_counts.min()

    # Tách từng lớp
    balanced_parts = []
    for cls in class_counts.index:
        df_cls = df[df[target_col] == cls]
        df_sample = df_cls.sample(min_count, random_state=random_state)
        balanced_parts.append(df_sample)

    # Ghép lại và shuffle
    df_balanced = pd.concat(balanced_parts).sample(frac=1, random_state=random_state).reset_index(drop=True)
    return df_balanced
df_balanced = undersample_dataframe(df, target_col='target')
print(df_balanced['target'].value_counts())  # Kiểm tra cân bằng

df_balanced.head()

# 1. Import thư viện
!pip install imbalanced-learn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

from imblearn.over_sampling import SMOTE

# 2. Chuẩn bị dữ liệu
selected_columns = [
    'PHUONG THUC CHO VAY', 'LOAIKH', 'SEX', 'CURRENCYCD', 'DESC_TIME',
    'MJACCTTYPDESC', 'ORGNAME', 'PARENTORGNAME', 'MUCDICHVAY',
    'BASE_BAL', 'CURR_BAL', 'DUNO_QD', 'LAISUAT', 'NHOMNOMOI'
]
df = df[selected_columns].copy()

sex_mapping = {'ONG': 'MR', 'MR': 'MR', 'BA': 'MRS', 'MRS': 'MRS', 'MS': 'MRS'}
df['SEX'] = df['SEX'].map(sex_mapping).fillna('UNKNOWN')

df['target'] = df['NHOMNOMOI'].apply(lambda x: 1 if x == 1 else 0)
df_model = df.drop(columns=['NHOMNOMOI'])

X = df_model.drop(columns=['target'])
y = df_model['target']

numerical_cols = ['BASE_BAL', 'CURR_BAL', 'DUNO_QD', 'LAISUAT']
categorical_cols = [col for col in X.columns if col not in numerical_cols]
for col in categorical_cols:
    X[col] = X[col].astype(str)

preprocessor = ColumnTransformer([
    ('num', StandardScaler(), numerical_cols),
    ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
])

# 3. Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# 4. Mô hình KHÔNG dùng SMOTE
pipeline_no_smote = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(solver='liblinear'))
])
pipeline_no_smote.fit(X_train, y_train)
y_pred_no_smote = pipeline_no_smote.predict(X_test)

print("=== 📘 Logistic Regression (No SMOTE) ===")
print(classification_report(y_test, y_pred_no_smote))
cm1 = confusion_matrix(y_test, y_pred_no_smote)
ConfusionMatrixDisplay(cm1).plot(cmap='Blues')
plt.title("Confusion Matrix - Logistic Regression (No SMOTE)")
plt.show()

# 5. Mô hình dùng SMOTE
# Tiền xử lý trước khi oversampling
X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed = preprocessor.transform(X_test)

smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_train_transformed, y_train)

model_smote = LogisticRegression(solver='liblinear')
model_smote.fit(X_resampled, y_resampled)
y_pred_smote = model_smote.predict(X_test_transformed)

print("=== 📗 Logistic Regression (With SMOTE) ===")
print(classification_report(y_test, y_pred_smote))
cm2 = confusion_matrix(y_test, y_pred_smote)
ConfusionMatrixDisplay(cm2).plot(cmap='Greens')
plt.title("Confusion Matrix - Logistic Regression (With SMOTE)")
plt.show()

# Cài thư viện nếu chưa có
!pip install xgboost imbalanced-learn

# Import thư viện
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# 1. Huấn luyện Random Forest
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_resampled, y_resampled)
y_pred_rf = rf_model.predict(X_test_processed)

# 2. Huấn luyện XGBoost
xgb_model = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)
xgb_model.fit(X_resampled, y_resampled)
y_pred_xgb = xgb_model.predict(X_test_processed)

# 3. Đánh giá Random Forest
print("=== 🌲 Random Forest (With SMOTE) ===")
print(classification_report(y_test, y_pred_rf))
cm_rf = confusion_matrix(y_test, y_pred_rf)
ConfusionMatrixDisplay(confusion_matrix=cm_rf).plot(cmap='Greens')
plt.title("Confusion Matrix - Random Forest")
plt.show()

# 4. Đánh giá XGBoost
print("=== ⚡ XGBoost (With SMOTE) ===")
print(classification_report(y_test, y_pred_xgb))
cm_xgb = confusion_matrix(y_test, y_pred_xgb)
ConfusionMatrixDisplay(confusion_matrix=cm_xgb).plot(cmap='Oranges')
plt.title("Confusion Matrix - XGBoost")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay, f1_score

# 1. Lấy xác suất dự đoán từ mô hình XGBoost
y_proba_xgb = xgb_model.predict_proba(X_test_processed)[:, 1]  # Xác suất thuộc lớp 1 (Good)

# 2. Duyệt qua nhiều ngưỡng để tìm threshold tốt nhất
thresholds = np.arange(0.1, 0.91, 0.05)
f1_scores = []

print("=== 🎯 F1-score theo các ngưỡng threshold ===")
for threshold in thresholds:
    y_pred_threshold = (y_proba_xgb >= threshold).astype(int)
    f1 = f1_score(y_test, y_pred_threshold, pos_label=0)  # Tập trung đánh giá lớp 'Bad'
    f1_scores.append(f1)
    print(f"Threshold: {threshold:.2f} | F1-score (Bad=0): {f1:.4f}")

# 3. Vẽ biểu đồ f1-score theo threshold
plt.figure(figsize=(8, 5))
plt.plot(thresholds, f1_scores, marker='o')
plt.xlabel("Threshold")
plt.ylabel("F1-score for class 'Bad'")
plt.title("🎯 F1-score for detecting Bad (label=0) vs Threshold")
plt.grid(True)
plt.show()

# 4. Chọn threshold tối ưu và đánh giá lại
best_threshold = thresholds[np.argmax(f1_scores)]
print(f"\n✅ Ngưỡng tốt nhất: {best_threshold:.2f} — F1-score (Bad=0): {max(f1_scores):.4f}")

# 5. Dự đoán lại với threshold tối ưu
y_pred_optimal = (y_proba_xgb >= best_threshold).astype(int)

print("\n=== ⚡ XGBoost (Threshold adjusted) ===")
print(classification_report(y_test, y_pred_optimal))
cm = confusion_matrix(y_test, y_pred_optimal)
ConfusionMatrixDisplay(confusion_matrix=cm).plot(cmap='Oranges')
plt.title(f"Confusion Matrix - XGBoost (Threshold = {best_threshold:.2f})")
plt.show()